// packages/angular/src/lib/components/widget/DomOSWidgetComponent.ts
import {
  Component,
  input,
  signal,
  computed,
  effect,
  OnDestroy,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {
  DomOSClient,
  generateWidgetStyles,
  generateId,
  DEFAULT_WIDGET_CONFIG,
  DEFAULT_THEME,
  DEFAULT_LABELS,
  type WidgetConfig,
  type WidgetMode,
  type WidgetVisualState,
  type WidgetMessage,
  type ClientState,
  type ApprovalRequest,
} from '@domos/core';
import { DomOSApprovalModalComponent } from '../hitl/DomOSApprovalModalComponent.js';

/**
 * DomOSWidgetComponent — Widget de chat vocal/texte standalone Angular.
 *
 * Surface widget officielle du SDK Angular, équivalent des widgets React/Vue/Svelte.
 * Gère autonomement le cycle de vie du client DomOS, l'audio bidirectionnel,
 * le texte, et la boucle HITL avec modal d'approbation intégrée.
 *
 * @example
 * ```typescript
 * import { DomOSWidgetComponent } from '@domos/angular';
 *
 * @Component({
 *   standalone: true,
 *   imports: [DomOSWidgetComponent],
 *   template: `
 *     <domos-widget
 *       [apiKey]="'pk_live_xxx'"
 *       [endpoint]="'wss://api.example.com/domos'"
 *       [config]="{ agentName: 'Alex', mode: 'audio' }"
 *     />
 *   `,
 * })
 * export class AppComponent {}
 * ```
 */
@Component({
  selector: 'domos-widget',
  standalone: true,
  imports: [CommonModule, FormsModule, DomOSApprovalModalComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="domos-widget-root">
      <!-- Inject widget CSS -->
      <style>{{ widgetCSS() }}</style>

      <!-- Floating Button (when closed) -->
      @if (!isOpen()) {
        <button
          [class]="'domos-fab ' + positionClass() + ' ' + presetClass()"
          [attr.aria-label]="cfg().labels.callToAction"
          (click)="handleOpen()"
        >
          @if (cfg().labels.badge) {
            <span class="domos-fab-badge">{{ cfg().labels.badge }}</span>
          }

          <div class="domos-fab-content">
            <span class="domos-fab-title">{{ cfg().labels.callToAction }}</span>
            <span class="domos-fab-subtitle">{{ cfg().labels.subtitle }}</span>
            <span class="domos-fab-signature">by DomOS AI</span>
          </div>

          <div class="domos-fab-icon">
            <svg viewBox="0 0 24 24">
              <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
            </svg>
          </div>
        </button>
      }

      <!-- Call Panel (when open) -->
      @if (isOpen()) {
        <div [class]="'domos-panel ' + positionClass() + ' ' + presetClass() + (currentMode() === 'text' ? ' text-mode' : '') + (isClosing() ? ' is-closing' : '')">

          <!-- Header -->
          <div class="domos-panel-header">
            <div class="domos-avatar">
              <svg viewBox="0 0 24 24">
                <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
                <circle cx="12" cy="7" r="4" />
              </svg>
            </div>

            <div class="domos-panel-info">
              <div class="domos-panel-name">{{ agentDisplay() }}</div>
              <div class="domos-panel-status">
                @if (dotClass()) {
                  <span [class]="'domos-status-dot ' + dotClass()"></span>
                }
                {{ statusLabel() }}
              </div>
            </div>

            <button class="domos-hangup-btn" (click)="handleHangUp()" [attr.aria-label]="cfg().labels.hangUp">
              <svg viewBox="0 0 24 24">
                <path d="M23 16.92V20a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.42 19.42 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 5.11 2h3.09a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 20 18.92V17m2.5-1.5L19 12"/>
              </svg>
            </button>
          </div>

          <!-- Messages (text mode) -->
          @if (currentMode() === 'text') {
            <div class="domos-messages">
              @for (msg of messages(); track msg.id) {
                <div [class]="'domos-message domos-message-' + msg.role">
                  <div class="domos-message-content">{{ msg.content }}</div>
                  <div class="domos-message-time">{{ formatTime(msg.timestamp) }}</div>
                </div>
              }
            </div>
          }

          <!-- Audio visualizer -->
          @if (currentMode() === 'audio') {
            <div class="domos-audio-visualizer">
              <div class="domos-waveform" [class.active]="visualState() === 'listening' || visualState() === 'speaking'">
                @for (bar of [0,1,2,3,4]; track bar) {
                  <div class="domos-wave-bar"></div>
                }
              </div>
              @if (isThinkingState()) {
                <div class="domos-thinking-pulse"></div>
              }
            </div>
          }

          <!-- Text Input -->
          @if (currentMode() === 'text') {
            <div class="domos-input-area">
              <input
                type="text"
                class="domos-text-input"
                [(ngModel)]="textInputValue"
                [placeholder]="cfg().labels.textPlaceholder"
                (keydown)="onKeyDown($event)"
                [disabled]="!isLive()"
              />
              <button class="domos-send-btn" (click)="onSend()" [disabled]="!textInputValue.trim() || !isLive()">
                <svg viewBox="0 0 24 24">
                  <path d="M22 2L11 13M22 2l-7 20-4-9-9-4 20-7z" />
                </svg>
              </button>
            </div>
          }

          <!-- Mode Toggle -->
          @if (cfg().allowModeSwitch) {
            <button class="domos-mode-toggle" (click)="handleSwitchMode()">
              @if (currentMode() === 'audio') {
                <svg viewBox="0 0 24 24"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>
                <span>Passer au texte</span>
              } @else {
                <svg viewBox="0 0 24 24"><path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2M12 19v4M8 23h8"/></svg>
                <span>Passer à l'audio</span>
              }
            </button>
          }
        </div>
      }

      <!-- Approval Modal -->
      <domos-approval-modal
        [request]="pendingApproval()"
        [open]="!!pendingApproval()"
        (approve)="approveAction()"
        (deny)="denyAction()"
      />
    </div>
  `,
})
export class DomOSWidgetComponent implements OnDestroy {
  // ---- Inputs ----
  apiKey = input<string | undefined>(undefined);
  endpoint = input<string | undefined>(undefined);
  client = input<DomOSClient | undefined>(undefined);
  config = input<WidgetConfig>({});
  showApprovalModal = input<boolean>(true);

  // ---- Merged config ----
  cfg = computed(() => ({
    ...DEFAULT_WIDGET_CONFIG,
    ...this.config(),
    theme: { ...DEFAULT_THEME, ...this.config()?.theme },
    labels: { ...DEFAULT_LABELS, ...this.config()?.labels },
  }));

  // ---- DomOS Client state ----
  private _client: DomOSClient | null = null;
  private _ownsClient = false;

  agentState = signal<ClientState>('disconnected');
  lastResponse = signal<string | null>(null);
  pendingApproval = signal<ApprovalRequest | null>(null);
  private approvalResolver: ((approved: boolean) => void) | null = null;
  lineState = signal<'idle' | 'waiting' | 'busy'>('idle');

  // ---- Widget state ----
  isOpen = signal(false);
  isClosing = signal(false);
  currentMode = signal<WidgetMode>(this.cfg().mode);
  messages = signal<WidgetMessage[]>([]);
  isRecording = signal(false);
  textInputValue = '';

  // Audio recording state
  private mediaStream: MediaStream | null = null;
  private audioContext: AudioContext | null = null;
  private processor: ScriptProcessorNode | null = null;

  // Audio playback state
  private playbackContext: AudioContext | null = null;
  private playbackNextStartTime = 0;

  // ---- CSS ----
  widgetCSS = computed(() =>
    generateWidgetStyles(this.cfg().theme, this.cfg().stylePreset, '.domos-widget-root')
  );

  // ---- Derived state ----
  visualState = computed<WidgetVisualState>(() => {
    const state = this.agentState();
    if (state === 'listening' || this.isRecording()) return 'listening';
    if (state === 'thinking') return 'thinking';
    if (state === 'speaking') return 'speaking';
    if (state === 'error' || state === 'disconnected') return 'error';
    return 'idle';
  });

  statusLabel = computed(() => {
    const state = this.visualState();
    const labels = this.cfg().labels;
    switch (state) {
      case 'listening': return labels.listening;
      case 'thinking': return labels.thinking;
      case 'speaking': return labels.speaking;
      case 'error': return labels.error;
      default: return labels.idle;
    }
  });

  dotClass = computed(() => {
    const visual = this.visualState();
    if (visual === 'error') return 'error';
    if (this.agentState() === 'disconnected') return 'offline';
    return '';
  });

  isLive = computed(() =>
    ['connected', 'listening', 'thinking', 'speaking'].includes(this.agentState())
  );

  agentDisplay = computed(() => {
    const c = this.cfg();
    return c.agentTitle ? `${c.agentName} (${c.agentTitle})` : c.agentName;
  });

  isThinkingState = computed(() => this.agentState() === 'thinking');

  positionClass = computed(() =>
    this.cfg().position === 'bottom-left' ? 'bottom-left' : ''
  );

  presetClass = computed(() => `domos-preset-${this.cfg().stylePreset}`);

  // ---- Track agent responses ----
  private prevResponse: string | null = null;

  constructor() {
    this.initializeClient();

    // Track agent responses and update messages
    effect(() => {
      const val = this.lastResponse();
      if (val && val !== this.prevResponse) {
        this.prevResponse = val;
        const msgs = this.messages();
        const last = msgs[msgs.length - 1];
        if (last?.role === 'agent') {
          this.messages.set([
            ...msgs.slice(0, -1),
            { ...last, content: val, timestamp: Date.now() },
          ]);
        } else {
          this.messages.set([
            ...msgs,
            { id: generateId(), role: 'agent', content: val, timestamp: Date.now() },
          ]);
        }
      }
    });
  }

  private initializeClient(): void {
    const providedClient = this.client();
    if (providedClient) {
      this._client = providedClient;
      this._ownsClient = false;
    } else {
      const ep = this.endpoint();
      const key = this.apiKey();
      if (!ep || key === undefined) {
        throw new Error('DomOSWidget: endpoint/apiKey requis si client non fourni');
      }

      this._client = new DomOSClient({
        endpoint: ep,
        apiKey: key,
        autoReconnect: true,
      });
      this._ownsClient = true;
    }

    this._client.on({
      onStateChange: (state: ClientState) => {
        this.agentState.set(state);
      },
      onAgentResponse: (text: string, done: boolean) => {
        this.lastResponse.set(text);
        this.agentState.set(done ? 'connected' : 'speaking');
      },
      onAudioOutput: (audioBase64: string, mimeType: string) => {
        this.playAudioChunk(audioBase64, mimeType);
      },
      onLineAcquired: (_ln: string, waiting: boolean) => {
        this.lineState.set(waiting ? 'waiting' : 'idle');
      },
      onLineBusy: () => {
        this.lineState.set('busy');
      },
      onLineReady: (_ln: string) => {
        this.lineState.set('idle');
      },
      onApprovalRequest: (request: ApprovalRequest, resolve: (approved: boolean) => void) => {
        this.pendingApproval.set(request);
        this.approvalResolver = (approved: boolean) => {
          resolve(approved);
          this.pendingApproval.set(null);
          this.approvalResolver = null;
        };
      },
    });

    if (this._ownsClient) {
      this._client.connect();
    }
  }

  ngOnDestroy(): void {
    this.stopRecordingInternal();
    if (this.playbackContext && this.playbackContext.state !== 'closed') {
      this.playbackContext.close().catch(() => {});
    }
    this.playbackContext = null;
    this.playbackNextStartTime = 0;
    if (this._ownsClient) {
      this._client?.destroy();
    }
    this._client = null;
  }

  // ---- Audio recording ----
  private async startRecordingInternal(): Promise<void> {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        audio: {
          sampleRate: 16000,
          channelCount: 1,
          echoCancellation: true,
          noiseSuppression: true,
        },
      });

      this.mediaStream = stream;
      this.audioContext = new AudioContext({ sampleRate: 16000 });
      const source = this.audioContext.createMediaStreamSource(stream);
      this.processor = this.audioContext.createScriptProcessor(4096, 1, 1);

      this.processor.onaudioprocess = (event) => {
        const pcmData = event.inputBuffer.getChannelData(0);
        const int16 = new Int16Array(pcmData.length);
        for (let i = 0; i < pcmData.length; i++) {
          const s = Math.max(-1, Math.min(1, pcmData[i]));
          int16[i] = s < 0 ? s * 0x8000 : s * 0x7fff;
        }
        const bytes = new Uint8Array(int16.buffer);
        let binary = '';
        for (let i = 0; i < bytes.length; i++) {
          binary += String.fromCharCode(bytes[i]);
        }
        this._client?.sendAudioStream(btoa(binary), 'audio/pcm;rate=16000');
      };

      source.connect(this.processor);
      this.processor.connect(this.audioContext.destination);
      this.isRecording.set(true);
    } catch {
      throw new Error('Microphone access denied');
    }
  }

  private stopRecordingInternal(): void {
    this.processor?.disconnect();
    this.audioContext?.close();
    this.mediaStream?.getTracks().forEach((t) => t.stop());
    this.processor = null;
    this.audioContext = null;
    this.mediaStream = null;
    this.isRecording.set(false);
  }

  // ---- Audio playback (voix de l'agent) ----
  private playAudioChunk(audioBase64: string, mimeType: string): void {
    try {
      if (!audioBase64) return;

      const rateMatch = mimeType.match(/rate=(\d+)/);
      const outputRate = rateMatch ? parseInt(rateMatch[1], 10) : 24000;

      if (!this.playbackContext || this.playbackContext.state === 'closed') {
        this.playbackContext = new AudioContext({ sampleRate: outputRate });
        this.playbackNextStartTime = 0;
      }

      const ctx = this.playbackContext;

      if (ctx.state === 'suspended') {
        ctx.resume().catch(() => {});
      }

      // Decoder base64 → Int16 PCM → Float32
      const binary = atob(audioBase64);
      const validLength = binary.length - (binary.length % 2);
      const bytes = new Uint8Array(validLength);
      for (let i = 0; i < validLength; i++) {
        bytes[i] = binary.charCodeAt(i);
      }
      const int16 = new Int16Array(bytes.buffer);
      const float32 = new Float32Array(int16.length);
      for (let i = 0; i < int16.length; i++) {
        float32[i] = int16[i] / 32768;
      }

      const buffer = ctx.createBuffer(1, float32.length, outputRate);
      buffer.getChannelData(0).set(float32);

      const source = ctx.createBufferSource();
      source.buffer = buffer;
      source.connect(ctx.destination);

      // Scheduling séquentiel : évite chevauchements et silences entre chunks
      const startTime = Math.max(ctx.currentTime, this.playbackNextStartTime);
      source.start(startTime);
      this.playbackNextStartTime = startTime + buffer.duration;
    } catch (err) {
      console.error('Erreur lecture audio:', err);
    }
  }

  // ---- Actions ----
  async handleOpen(): Promise<void> {
    this.isOpen.set(true);
    this.isClosing.set(false);

    if (this.cfg().mode === 'audio') {
      try {
        await this.startRecordingInternal();
      } catch {
        if (this.cfg().fallbackToText) {
          this.currentMode.set('text');
        }
      }
    }
  }

  handleHangUp(): void {
    if (this.isRecording()) this.stopRecordingInternal();

    this.isClosing.set(true);
    setTimeout(() => {
      this.isOpen.set(false);
      this.isClosing.set(false);
      this.messages.set([]);
    }, 250);
  }

  private handleSendText(text: string): void {
    const trimmed = text.trim();
    if (!trimmed || !this._client) return;

    this.messages.set([
      ...this.messages(),
      { id: generateId(), role: 'user', content: trimmed, timestamp: Date.now() },
    ]);
    this._client.sendText(trimmed);
  }

  async handleSwitchMode(): Promise<void> {
    if (this.currentMode() === 'audio') {
      if (this.isRecording()) this.stopRecordingInternal();
      this.currentMode.set('text');
    } else {
      this.currentMode.set('audio');
      try {
        await this.startRecordingInternal();
      } catch {
        if (this.cfg().fallbackToText) this.currentMode.set('text');
      }
    }
  }

  // ---- Text input ----
  onSend(): void {
    this.handleSendText(this.textInputValue);
    this.textInputValue = '';
  }

  onKeyDown(e: KeyboardEvent): void {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      this.onSend();
    }
  }

  formatTime(ts: number): string {
    return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  }

  // ---- Approval actions ----
  approveAction(): void {
    this.approvalResolver?.(true);
  }

  denyAction(): void {
    this.approvalResolver?.(false);
  }
}

// packages/svelte/src/components/widget/DomOSWidget.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import {
    DomOSClient,
    generateWidgetStyles,
    generateId,
    DEFAULT_WIDGET_CONFIG,
    DEFAULT_THEME,
    DEFAULT_LABELS,
    type WidgetConfig,
    type WidgetMode,
    type WidgetVisualState,
    type WidgetMessage,
    type ClientState,
    type ApprovalRequest,
  } from '@domos/core';
  import ApprovalModal from '../hitl.ApprovalModal.svelte';

  // ---- Props ----
  let { apiKey, endpoint, client: providedClient = null, config = {} }: {
    apiKey?: string;
    endpoint?: string;
    client?: DomOSClient;
    config?: WidgetConfig;
  } = $props();

  // ---- Merged config ----
  const cfg = $derived({
    ...DEFAULT_WIDGET_CONFIG,
    ...config,
    theme: { ...DEFAULT_THEME, ...config?.theme },
    labels: { ...DEFAULT_LABELS, ...config?.labels },
  });

  // ---- DomOS Client ----
  let client: DomOSClient | null = null;
  let ownsClient = false;
  let agentState = $state<ClientState>('disconnected');
  let lastResponse = $state<string | null>(null);
  let pendingApproval = $state<ApprovalRequest | null>(null);
  let approvalResolver: ((approved: boolean) => void) | null = null;

  // ---- Widget state ----
  let isOpen = $state(false);
  let isClosing = $state(false);
  let currentMode = $state<WidgetMode>(cfg.mode);
  let messages = $state<WidgetMessage[]>([]);
  let isRecording = $state(false);
  let textInput = $state('');

  // Audio recording state
  let mediaStream: MediaStream | null = null;
  let audioContext: AudioContext | null = null;
  let processor: ScriptProcessorNode | null = null;

  // Audio playback state (pour recevoir la voix de l'agent)
  let playbackContext: AudioContext | null = null;
  let nextStartTime = 0;

  // ---- CSS ----
  const widgetCSS = $derived(generateWidgetStyles(cfg.theme, cfg.stylePreset));

  // ---- Derived state ----
  const visualState = $derived((() => {
    if (agentState === 'listening' || isRecording) return 'listening' as WidgetVisualState;
    if (agentState === 'thinking') return 'thinking' as WidgetVisualState;
    if (agentState === 'speaking') return 'speaking' as WidgetVisualState;
    if (agentState === 'error' || agentState === 'disconnected') return 'error' as WidgetVisualState;
    return 'idle' as WidgetVisualState;
  })());

  const statusLabel = $derived((() => {
    switch (visualState) {
      case 'listening': return cfg.labels.listening;
      case 'thinking':  return cfg.labels.thinking;
      case 'speaking':  return cfg.labels.speaking;
      case 'error':     return cfg.labels.error;
      default:          return cfg.labels.idle;
    }
  })());

  const dotClass = $derived((() => {
    if (visualState === 'error') return 'error';
    if (agentState === 'disconnected') return 'offline';
    return '';
  })());

  const isLive = $derived(['connected', 'listening', 'thinking', 'speaking'].includes(agentState));

  const agentDisplay = $derived(cfg.agentTitle
    ? `${cfg.agentName} (${cfg.agentTitle})`
    : cfg.agentName);

  const isThinkingState = $derived(agentState === 'thinking');

  const positionClass = $derived(cfg.position === 'bottom-left' ? 'bottom-left' : '');
  const presetClass = $derived(`domos-preset-${cfg.stylePreset}`);

  // ---- Track agent responses ----
  let prevResponse: string | null = null;
  $effect(() => {
    if (lastResponse && lastResponse !== prevResponse) {
      prevResponse = lastResponse;
      const last = messages[messages.length - 1];
      if (last?.role === 'agent') {
        messages = [
          ...messages.slice(0, -1),
          { ...last, content: lastResponse, timestamp: Date.now() },
        ];
      } else {
        messages = [...messages, {
          id: generateId(),
          role: 'agent',
          content: lastResponse,
          timestamp: Date.now(),
        }];
      }
    }
  });

  // ---- Lifecycle ----
  onMount(() => {
    if (providedClient) {
      client = providedClient;
      ownsClient = false;
    } else {
      if (!endpoint || apiKey === undefined) {
        throw new Error('DomOSWidget: endpoint/apiKey requis si client non fourni');
      }

      client = new DomOSClient({
        endpoint,
        apiKey,
        autoReconnect: true,
      });
      ownsClient = true;
    }

    client.on({
      onStateChange: (state: ClientState) => {
        agentState = state;
      },
      onAgentResponse: (text: string, done: boolean) => {
        lastResponse = text;
        agentState = done ? 'connected' : 'speaking';
      },
      onAudioOutput: (audioBase64: string, mimeType: string) => {
        playAudioChunk(audioBase64, mimeType);
      },
      onApprovalRequest: (request: ApprovalRequest, resolve: (approved: boolean) => void) => {
        pendingApproval = request;
        approvalResolver = (approved: boolean) => {
          resolve(approved);
          pendingApproval = null;
          approvalResolver = null;
        };
      },
    });

    if (ownsClient) {
      client.connect();
    }
  });

  onDestroy(() => {
    stopRecordingInternal();
    if (playbackContext && playbackContext.state !== 'closed') {
      void playbackContext.close().catch(() => {});
    }
    playbackContext = null;
    nextStartTime = 0;
    if (ownsClient) {
      client?.destroy();
    }
    client = null;
  });

  // ---- Audio recording ----
  async function startRecordingInternal() {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        audio: { sampleRate: 16000, channelCount: 1, echoCancellation: true, noiseSuppression: true },
      });

      mediaStream = stream;
      audioContext = new AudioContext({ sampleRate: 16000 });
      const source = audioContext.createMediaStreamSource(stream);
      processor = audioContext.createScriptProcessor(4096, 1, 1);

      processor.onaudioprocess = (event) => {
        const pcmData = event.inputBuffer.getChannelData(0);
        const int16 = new Int16Array(pcmData.length);
        for (let i = 0; i < pcmData.length; i++) {
          const s = Math.max(-1, Math.min(1, pcmData[i]));
          int16[i] = s < 0 ? s * 0x8000 : s * 0x7fff;
        }
        const bytes = new Uint8Array(int16.buffer);
        let binary = '';
        for (let i = 0; i < bytes.length; i++) {
          binary += String.fromCharCode(bytes[i]);
        }
        client?.sendAudioStream(btoa(binary), 'audio/pcm;rate=16000');
      };

      source.connect(processor);
      processor.connect(audioContext.destination);
      isRecording = true;
    } catch {
      throw new Error('Microphone access denied');
    }
  }

  function stopRecordingInternal() {
    processor?.disconnect();
    audioContext?.close();
    mediaStream?.getTracks().forEach((t) => t.stop());
    processor = null;
    audioContext = null;
    mediaStream = null;
    isRecording = false;
  }

  // ---- Audio playback (voix de l'agent) ----
  function playAudioChunk(audioBase64: string, mimeType: string) {
    try {
      if (!audioBase64) return;

      const rateMatch = mimeType.match(/rate=(\d+)/);
      const outputRate = rateMatch ? parseInt(rateMatch[1], 10) : 24000;

      if (!playbackContext || playbackContext.state === 'closed') {
        playbackContext = new AudioContext({ sampleRate: outputRate });
        nextStartTime = 0;
      }

      const ctx = playbackContext;

      if (ctx.state === 'suspended') {
        void ctx.resume().catch(() => {});
      }

      // Decoder base64 → Int16 PCM → Float32
      // validLength : aligner sur 2 octets pour éviter la corruption Int16Array
      const binary = atob(audioBase64);
      const validLength = binary.length - (binary.length % 2);
      const bytes = new Uint8Array(validLength);
      for (let i = 0; i < validLength; i++) {
        bytes[i] = binary.charCodeAt(i);
      }
      const int16 = new Int16Array(bytes.buffer);
      const float32 = new Float32Array(int16.length);
      for (let i = 0; i < int16.length; i++) {
        float32[i] = int16[i] / 32768;
      }

      const buffer = ctx.createBuffer(1, float32.length, outputRate);
      buffer.getChannelData(0).set(float32);

      const source = ctx.createBufferSource();
      source.buffer = buffer;
      source.connect(ctx.destination);

      // Scheduling séquentiel : évite chevauchements et silences entre chunks
      const startTime = Math.max(ctx.currentTime, nextStartTime);
      source.start(startTime);
      nextStartTime = startTime + buffer.duration;
    } catch (err) {
      console.error('Erreur lecture audio:', err);
    }
  }

  // ---- Actions ----
  async function handleOpen() {
    isOpen = true;
    isClosing = false;

    if (cfg.mode === 'audio') {
      try {
        await startRecordingInternal();
      } catch {
        if (cfg.fallbackToText) {
          currentMode = 'text';
        }
      }
    }
  }

  function handleHangUp() {
    if (isRecording) stopRecordingInternal();

    isClosing = true;
    setTimeout(() => {
      isOpen = false;
      isClosing = false;
      messages = [];
    }, 250);
  }

  function handleSendText(text: string) {
    const trimmed = text.trim();
    if (!trimmed || !client) return;

    messages = [...messages, {
      id: generateId(),
      role: 'user',
      content: trimmed,
      timestamp: Date.now(),
    }];
    client.sendText(trimmed);
  }

  async function handleSwitchMode() {
    if (currentMode === 'audio') {
      if (isRecording) stopRecordingInternal();
      currentMode = 'text';
    } else {
      currentMode = 'audio';
      try {
        await startRecordingInternal();
      } catch {
        if (cfg.fallbackToText) currentMode = 'text';
      }
    }
  }

  function onSend() {
    handleSendText(textInput);
    textInput = '';
  }

  function onKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      onSend();
    }
  }

  function formatTime(ts: number): string {
    return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  }

  function approveAction() {
    approvalResolver?.(true);
  }

  function denyAction() {
    approvalResolver?.(false);
  }
</script>

<!-- Inject widget CSS -->
<svelte:head>
  {@html `<style>${widgetCSS}</style>`}
</svelte:head>

<!-- Floating Button (when closed) -->
{#if !isOpen}
  <button
    class="domos-fab {positionClass} {presetClass}"
    aria-label={cfg.labels.callToAction}
    onclick={handleOpen}
  >
    {#if cfg.labels.badge}
      <span class="domos-fab-badge">{cfg.labels.badge}</span>
    {/if}

    <div class="domos-fab-content">
      <span class="domos-fab-title">{cfg.labels.callToAction}</span>
      <span class="domos-fab-subtitle">{cfg.labels.subtitle}</span>
      <span class="domos-fab-signature">by DomOS AI</span>
    </div>

    <div class="domos-fab-icon">
      <svg viewBox="0 0 24 24">
        <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
      </svg>
    </div>
  </button>
{/if}

<!-- Call Panel (when open) -->
{#if isOpen}
  <div class="domos-panel {positionClass} {presetClass} {currentMode === 'text' ? 'text-mode' : ''} {isClosing ? 'is-closing' : ''}">

    <!-- Header -->
    <div class="domos-panel-header">
      <div class="domos-avatar">
        <svg viewBox="0 0 24 24">
          <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
          <circle cx="12" cy="7" r="4" />
        </svg>
      </div>

      <div class="domos-agent-info">
        <div class="domos-agent-name">{agentDisplay}</div>
        <div class="domos-agent-status">
          <span class="domos-status-dot {dotClass}" />
          <span>{statusLabel}</span>
        </div>
      </div>

      {#if isLive}
        <span class="domos-live-badge">{cfg.labels.live}</span>
      {/if}

      <!-- Header action buttons -->
      <div class="domos-header-actions">
        {#if cfg.allowModeSwitch}
          <button
            class="domos-btn-header {currentMode === 'text' ? 'active' : ''}"
            aria-label={currentMode === 'audio' ? 'Mode texte' : 'Mode audio'}
            onclick={handleSwitchMode}
          >
            {#if currentMode === 'audio'}
              <!-- Keyboard icon -->
              <svg viewBox="0 0 24 24">
                <rect x="2" y="4" width="20" height="16" rx="2" />
                <line x1="6" y1="8" x2="6" y2="8" />
                <line x1="10" y1="8" x2="10" y2="8" />
                <line x1="14" y1="8" x2="14" y2="8" />
                <line x1="18" y1="8" x2="18" y2="8" />
                <line x1="8" y1="16" x2="16" y2="16" />
              </svg>
            {:else}
              <!-- Mic icon -->
              <svg viewBox="0 0 24 24">
                <path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z" />
                <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                <line x1="12" y1="19" x2="12" y2="23" />
              </svg>
            {/if}
            <span class="domos-tooltip">
              {currentMode === 'audio' ? 'Mode texte' : 'Mode audio'}
            </span>
          </button>
        {/if}
      </div>
    </div>

    <!-- Body: Audio mode -->
    {#if currentMode === 'audio'}
      <div class="domos-panel-body">
        <div class="domos-audio-dots {visualState}">
          <div class="domos-audio-dot" />
          <div class="domos-audio-dot" />
          <div class="domos-audio-dot" />
          <div class="domos-audio-dot" />
          <div class="domos-audio-dot" />
        </div>
      </div>
    {:else}
      <!-- Body: Text mode (messages) -->
      <div class="domos-messages">
        {#if messages.length === 0 && !isThinkingState}
          <div class="domos-empty">
            Envoyez un message pour d&eacute;marrer.
          </div>
        {/if}

        {#each messages as msg (msg.id)}
          <div class="domos-msg {msg.role}">
            <div>{msg.content}</div>
            <div class="domos-msg-time">{formatTime(msg.timestamp)}</div>
          </div>
        {/each}

        {#if isThinkingState}
          <div class="domos-typing">
            <div class="domos-typing-dot" />
            <div class="domos-typing-dot" />
            <div class="domos-typing-dot" />
          </div>
        {/if}
      </div>

      <!-- Text input bar -->
      <div class="domos-text-bar">
        <input
          bind:value={textInput}
          type="text"
          class="domos-text-input"
          placeholder={cfg.labels.textPlaceholder}
          onkeydown={onKeyDown}
        />
        <button
          class="domos-btn-send"
          disabled={!textInput.trim()}
          aria-label={cfg.labels.send}
          onclick={onSend}
        >
          <svg viewBox="0 0 24 24">
            <line x1="22" y1="2" x2="11" y2="13" />
            <polygon points="22 2 15 22 11 13 2 9 22 2" />
          </svg>
        </button>
      </div>
    {/if}

    <!-- Footer -->
    <div class="domos-panel-footer">
      <button class="domos-btn-hangup" onclick={handleHangUp}>
        <svg viewBox="0 0 24 24">
          <line x1="18" y1="6" x2="6" y2="18" />
          <line x1="6" y1="6" x2="18" y2="18" />
        </svg>
        {cfg.labels.hangUp}
      </button>

      {#if cfg.allowModeSwitch}
        <button class="domos-btn-switch" onclick={handleSwitchMode}>
          {currentMode === 'audio' ? 'Passer en mode texte' : 'Passer en mode audio'}
        </button>
      {/if}
    </div>
    <div class="domos-widget-signature">by DomOS AI</div>
  </div>
{/if}

{#if pendingApproval}
  <ApprovalModal
    toolName={pendingApproval.toolName}
    message={pendingApproval.message}
    risk={pendingApproval.risk}
    args={pendingApproval.args}
    onapprove={approveAction}
    ondeny={denyAction}
  />
{/if}
